### ISSUE TITLE
The TACACS+ Implementation is Secure

### ISSUE THREAD

**Issue by meltyness** [meltyness/ratchet#9]
This epic describes the engineering design of ratchet from a security perspective:

- [ ] External interfaces of the server are written in Rust, and benefit from memory safety guarantees.
    - [x] Management plane interfaces
    - [ ] Auditing plane interface
    - [x] Data plane interfaces
- [ ] The relationship between the operating system, libraries, and the server application is audited automatically for key security assumptions, and can be considered secure.
    - [ ] Consider an eBPF fail2ban to efficiently implement throttling / prevent resource exhaustion
    - [ ] Sufficient unit, integration tests, or static analyses or ideally compile-time guarantees provide ongoing artifacts supporting that this is the case
- [ ] The implementation, or its use, will not under any circumstances write sensitive information to disk.
    - [x] To that, passwords do not need to be stored in a recoverable format -- for PAP/ASCII we can simply compare to some salt/hash version of the passwords.
    - [ ] A safe should protect the user password too (whichever field this protocol will dump it in) 
- [ ] The system is resistant to amplification, resource exhaustion, or DoS attacks from outside or misconfigured systems.
    - [x] One specific case is within ASCII authentication that the system must service an interactive TCP session and so must be performed asynchronously to prevent DoS. This implies a time-bound buffer for which a malicious authenticated attacker can consume line-rate-order resources. 
    - [x] The relationship between long-polling and the credentials/clients containers must not be a deadlock condition.
    - [ ] Fast drop on missing / hanging headers
- [ ] The system correctly implements the protocol
    - [ ] *it's not clear that this is even possible, there are gaps.*
- [ ] The system implements fault isolation correctly:
    - [ ] Individual faults don't fault whole collections
- [ ] There's a warning label that TACACS+ basically shouldn't be used because it is an inherently insecure mechanism (see: https://agrrrdog.blogspot.com/2015/11/3-attacks-on-cisco-tacacs-bypassing.html)
